---
- name: Create front-end web server EC2 instances
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{castle_gate_name}}"
    instance_type: "{{instance_type}}"
    assign_public_ip: no
    instance_profile_name: "{{tag_prefix}}{{castle_gate_name}}-profile"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    volumes:
      - device_name: /dev/sda1
        device_type: standard
        volume_size: 8
        delete_on_termination: true
    wait: yes
    user_data: "{{ lookup('template', '../templates/castle-gate-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{tag_prefix}}archi"
      profile: "web"
    count_tag:
      prefix: "{{tag_prefix}}archi"
      profile: "web"
    exact_count: 1
  register: web_servers

- name: Association of elastic ip address to web-front
  local_action:
     module: command
       aws ec2 associate-address --instance-id "{{ web_servers.instances[0].id }}" --public-ip "{{wb_elastic_ip}}"

- route53:
    command: create
    zone: "{{tag_prefix}}ec2.internal."
    record: "web.{{tag_prefix}}ec2.internal."
    private_zone: yes
    type: A
    value: "{{web_servers.instances[0].private_ip}}"
    overwrite: yes
