# XXX Until Ansible v2 is widely available:
# We run all native Ansible commands before awscli commands because those
# later could fail if the resources do not exist. None-the-less here we
# need to create the bucket after the roles were created.

- name: Creating groups and roles
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
     deployuser: "{{ lookup('env','LOGNAME') }}"
  roles:
    - keyimport
    - creategroups
    - createiamroles
    - creates3bucket
    - createprivatedns

